# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 13 * * 1,5"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ninjakx
          template: classic
          base: header, activity, community, repositories
          config_display: large
          config_timezone: Asia/Kolkata
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B

          plugin_stackoverflow: yes
          plugin_stackoverflow_limit: 0
          plugin_stackoverflow_lines: 0
          plugin_stackoverflow_lines_snippet: 0
          plugin_stackoverflow_sections: None
          plugin_stackoverflow_user: 6660373
          
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          

#           plugin_gists: yes
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_categories: markup, programming, html, css, HTML, SCSS, CSS
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming, HTML, SCSS, CSS
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes

          repositories_affiliations: public

#         ============ ANIME ===============
          plugin_anilist: yes
          plugin_anilist_limit: 5
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_user: nkx
          
#         =============== TOPIC ==============
          filename: metrics.plugin.topics.svg
          plugin_topics: yes
          plugin_topics_limit: 12
          
          config_padding: 0%
