# See https://github.com/lowlighter/metrics for documentation
# This worflow is scheduled for every hour, and also run after each commit (GitHub action excluded) on master/main branch

name: Metrics
on:
  schedule:
    - cron: "0 0-23/4 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
    
       # ======================================================================================
      # 🌸 Anilist

      # Anilist with onlyt favorites and currently watching anime sections
      - name: 🌸 Anilist plugin (favorites and currently watching)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.anilist.svg
          token: NOT_NEEDED
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_user: nkx
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 1
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      # Anilist with only favorites and currently reading manga sections
      - name: 🌸 Anilist plugin (favorites and currently reading)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.anilist.manga.svg
          token: NOT_NEEDED
          plugin_anilist: yes
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites, reading
          plugin_anilist_limit: 1
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      # Anilist with only favorites characters section
      - name: 🌸 Anilist plugin (favorites characters)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.anilist.characters.svg
          token: NOT_NEEDED
          plugin_anilist: yes
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 22
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      # Anilist plugin with all sections
      - name: 🌸 Anilist plugin (complete)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.anilist.full.svg
          token: NOT_NEEDED
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, watching, reading, characters
          plugin_anilist_limit: 1
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      - name: Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ninjakx
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: columns
          config_timezone: Asia/Kolkata
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_gists: yes
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_stackoverflow: yes
          plugin_stackoverflow_limit: 2
          plugin_stackoverflow_lines: 4
          plugin_stackoverflow_lines_snippet: 2
          plugin_stackoverflow_sections: answers-top, questions-top
          plugin_stackoverflow_user: 6660373
          repositories_affiliations: public
          
  
